steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cf01-2a023/cf01img:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cf01-2a023/cf01img:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'cf01img', '--region=us-central1', '--platform=managed', '--image=gcr.io/cf01-2a023/cf01img:$SHORT_SHA']
