steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/CF01/cf01_img:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/CF01/cf01_img:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'cf01_img', '--region=us-central1', '--platform=managed', '--image=gcr.io/CF01/cf01_img:$SHORT_SHA']